version: '3.7'


services:
 mariadb:
  image: mariadb
  container_name: mariadb
  build: ./requirements/mariadb/
  volumes:
   - db:/var/lib/mysql
  networks:
    - inception-network
  env_file: .env
  restart: always

 
 nginx:
  image: nginx
  container_name: nginx
  build: ./requirements/nginx/
  volumes:
   - wp:/var/www/html

  networks:
    - inception-network
  env_file: .env
  restart: always
  depends_on:
    - wordpress
  ports:
   - "443:443"

 wordpress:
  image: wordpress
  container_name: wordpress
  volumes:
   - wp:/var/www/html
  build: ./requirements/wordpress/
  networks:
    - inception-network
  env_file: .env
  restart: always
  depends_on:
    - mariadb


volumes:
  wp:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/btwee/data/wp
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/btwee/data/db

networks:
  inception-network:
    name: inception-network
    driver: bridge